modLoader = "javafml"
loaderVersion = "[2,)"
#issueTrackerURL = ""
license = "Apache 2.0"

[[mods]]
modId = "logicred"
version = "${version}"
displayName = "LogicRed"
authors = ""
description = '''
A mod that adds logical redstone and semi-realistic networking.
'''
#logoFile = ""

[[dependencies.logicred]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.logicred]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.logicred]]
modId = "architectury"
type = "required"
versionRange = "[13.0.8,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "logicred.mixins.json"
